# Setup
title: Shashank Kalanithi
tagline: Data Analytics Professional
url: https://kshashank03.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Shashank Kalanithi
  url: https://twitter.com/kalamari95
  email: 

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Consulting
    url: /consulting
   
  - title: DataScience
    url: /data_science

  - title: Resume
    url: /resume

  - title: BookClub
    url: /book_club

  - title: Blog
    url: /archive

  - title: About
    url: /about
